import { AttendanceRecord } from '../types/attendance-types';

// In-memory attendance store (companyId -> AttendanceRecord[])
export const memoryAttendanceRecords: Record<string, AttendanceRecord[]> = {
  comp_001: [
    {
      id: 'att_demo_01',
      companyId: 'comp_001',
      userId: 'user_owner_001',
      employeeName: 'Alex Carter',
      employeeEmail: 'admin@avexcrm.com',
      employeeRole: 'COMPANY_OWNER',
      date: new Date().toISOString().split('T')[0],
      clockIn: new Date(new Date().setHours(8, 55, 0, 0)).toISOString(),
      clockOut: null,
      status: 'PRESENT',
      workingMinutes: 240,
      notes: 'Morning sprint standup & deployment',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'att_demo_02',
      companyId: 'comp_001',
      userId: 'usr_002',
      employeeName: 'Sarah Jenkins',
      employeeEmail: 'sarah@avexcrm.com',
      employeeRole: 'ADMIN',
      date: new Date().toISOString().split('T')[0],
      clockIn: new Date(new Date().setHours(9, 25, 0, 0)).toISOString(),
      clockOut: null,
      status: 'LATE',
      workingMinutes: 210,
      notes: 'Delayed due to client call',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'att_demo_03',
      companyId: 'comp_001',
      userId: 'usr_003',
      employeeName: 'Marcus Vance',
      employeeEmail: 'marcus@avexcrm.com',
      employeeRole: 'EMPLOYEE',
      date: new Date().toISOString().split('T')[0],
      clockIn: new Date(new Date().setHours(9, 0, 0, 0)).toISOString(),
      clockOut: new Date(new Date().setHours(17, 30, 0, 0)).toISOString(),
      status: 'PRESENT',
      workingMinutes: 510,
      notes: 'Completed task sprint',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Past historical records
    {
      id: 'att_demo_hist_01',
      companyId: 'comp_001',
      userId: 'usr_001',
      employeeName: 'Alex Carter',
      employeeEmail: 'admin@avexcrm.com',
      employeeRole: 'COMPANY_OWNER',
      date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
      clockIn: new Date(Date.now() - 86400000 + 3600000 * 9).toISOString(),
      clockOut: new Date(Date.now() - 86400000 + 3600000 * 17.5).toISOString(),
      status: 'PRESENT',
      workingMinutes: 510,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'att_demo_hist_02',
      companyId: 'comp_001',
      userId: 'usr_001',
      employeeName: 'Alex Carter',
      employeeEmail: 'admin@avexcrm.com',
      employeeRole: 'COMPANY_OWNER',
      date: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0],
      clockIn: new Date(Date.now() - 86400000 * 2 + 3600000 * 9.5).toISOString(),
      clockOut: new Date(Date.now() - 86400000 * 2 + 3600000 * 18).toISOString(),
      status: 'LATE',
      workingMinutes: 510,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
};
