import { CalendarEvent } from '../types/calendar-types';

// In-memory store for custom/manual calendar events
export const memoryCustomEvents: Record<string, CalendarEvent[]> = {
  comp_001: [
    {
      id: 'evt_demo_01',
      companyId: 'comp_001',
      title: 'Q3 Enterprise Strategy & Roadmap Review',
      description: 'Quarterly executive review of project milestones, delivery timelines, and client engagements.',
      eventType: 'MEETING',
      status: 'SCHEDULED',
      startTime: new Date(new Date().setHours(10, 0, 0, 0)).toISOString(),
      endTime: new Date(new Date().setHours(11, 30, 0, 0)).toISOString(),
      allDay: false,
      location: 'Main Executive Boardroom / Hybrid',
      meetingLink: 'https://meet.google.com/avex-q3-strategy',
      linkPlatform: 'Google Meet',
      isClientVisible: false,
      organizer: { id: 'usr_001', fullName: 'Alex Carter', email: 'admin@avexcrm.com' },
      project: { id: 'proj_001', name: 'Cloud Platform Migration', projectCode: 'PRJ-1001' },
      reminderMinutes: 15,
      originSource: 'MANUAL',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'evt_demo_02',
      companyId: 'comp_001',
      title: 'Client Review Call: Cloud Infrastructure Delivery',
      description: 'Bi-weekly status checkpoint and deliverable walkthrough with client leadership.',
      eventType: 'CLIENT_MEETING',
      status: 'CONFIRMED',
      startTime: new Date(Date.now() + 86400000 * 2).toISOString(),
      endTime: new Date(Date.now() + 86400000 * 2 + 3600000).toISOString(),
      allDay: false,
      location: 'Zoom Conference Call',
      meetingLink: 'https://zoom.us/j/9842019482',
      linkPlatform: 'Zoom',
      isClientVisible: true,
      organizer: { id: 'usr_001', fullName: 'Alex Carter', email: 'admin@avexcrm.com' },
      customer: { id: 'cust_001', name: 'Sarah Jenkins', companyName: 'Acme Global Enterprises' },
      project: { id: 'proj_001', name: 'Cloud Platform Migration', projectCode: 'PRJ-1001' },
      reminderMinutes: 30,
      originSource: 'MEETING',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'evt_demo_03',
      companyId: 'comp_001',
      title: 'Follow-up: Enterprise License Proposal',
      description: 'Sales lead follow-up call with prospective enterprise buyer.',
      eventType: 'FOLLOW_UP',
      status: 'SCHEDULED',
      startTime: new Date(Date.now() + 86400000 * 4).toISOString(),
      endTime: new Date(Date.now() + 86400000 * 4 + 1800000).toISOString(),
      allDay: false,
      location: 'Phone Call (+1 800-555-0199)',
      isClientVisible: false,
      customer: { id: 'cust_002', name: 'David Vance', companyName: 'Starlight Media' },
      reminderMinutes: 15,
      originSource: 'MANUAL',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
};
