import {
  InventoryItemRecord,
  InventoryStockMovementRecord,
} from '../types/inventory-types';

export const memoryInventoryItems: Record<string, InventoryItemRecord[]> = {
  comp_001: [
    {
      id: 'item_demo_01',
      companyId: 'comp_001',
      sku: 'PRD-MAC-01',
      name: 'Apple MacBook Pro 16" M3 Max',
      description: '36GB Unified Memory, 1TB SSD, Space Black. Standard engineering laptop.',
      category: 'Hardware',
      unit: 'units',
      costPrice: 2899.0,
      sellPrice: 3499.0,
      reorderThreshold: 5,
      currentStock: 14,
      isLowStock: false,
      isActive: true,
      createdAt: '2024-01-10T09:00:00.000Z',
      updatedAt: '2026-08-26T10:00:00.000Z',
    },
    {
      id: 'item_demo_02',
      companyId: 'comp_001',
      sku: 'PRD-MON-02',
      name: 'Dell UltraSharp 32" 4K USB-C Hub Monitor',
      description: 'IPS Black panel, 90W power delivery, RJ45 Ethernet, calibrated sRGB.',
      category: 'Peripherals',
      unit: 'units',
      costPrice: 650.0,
      sellPrice: 899.99,
      reorderThreshold: 5,
      currentStock: 4,
      isLowStock: true,
      isActive: true,
      createdAt: '2024-02-15T09:00:00.000Z',
      updatedAt: '2026-08-26T10:00:00.000Z',
    },
    {
      id: 'item_demo_03',
      companyId: 'comp_001',
      sku: 'PRD-KEY-03',
      name: 'Logitech MX Mechanical Wireless Keyboard',
      description: 'Tactile Quiet switches, dual OS layout, USB-C fast charging.',
      category: 'Peripherals',
      unit: 'pcs',
      costPrice: 110.0,
      sellPrice: 169.99,
      reorderThreshold: 10,
      currentStock: 25,
      isLowStock: false,
      isActive: true,
      createdAt: '2024-03-01T09:00:00.000Z',
      updatedAt: '2026-08-26T10:00:00.000Z',
    },
    {
      id: 'item_demo_04',
      companyId: 'comp_001',
      sku: 'PRD-DESK-04',
      name: 'ErgoFlex Pro Motorized Standing Desk 60"',
      description: 'Dual motors, programmable memory presets, solid oak tabletop.',
      category: 'Furniture',
      unit: 'units',
      costPrice: 420.0,
      sellPrice: 699.0,
      reorderThreshold: 3,
      currentStock: 0,
      isLowStock: true,
      isActive: true,
      createdAt: '2024-04-10T09:00:00.000Z',
      updatedAt: '2026-08-26T10:00:00.000Z',
    },
    {
      id: 'item_demo_05',
      companyId: 'comp_001',
      sku: 'PRD-CHAIR-05',
      name: 'Herman Miller Aeron Ergonomic Chair',
      description: 'Size B, PostureFit SL, fully adjustable arms, graphite frame.',
      category: 'Furniture',
      unit: 'units',
      costPrice: 950.0,
      sellPrice: 1395.0,
      reorderThreshold: 2,
      currentStock: 8,
      isLowStock: false,
      isActive: true,
      createdAt: '2024-05-01T09:00:00.000Z',
      updatedAt: '2026-08-26T10:00:00.000Z',
    },
  ],
};

export const memoryInventoryMovements: Record<string, InventoryStockMovementRecord[]> = {
  comp_001: [
    {
      id: 'mov_demo_01',
      companyId: 'comp_001',
      itemId: 'item_demo_01',
      type: 'STOCK_IN',
      quantity: 20,
      reason: 'Initial hardware fleet purchase order #PO-941',
      performedByUserId: 'user_owner_001',
      createdAt: '2024-01-10T09:30:00.000Z',
      performedByUser: {
        id: 'user_owner_001',
        fullName: 'Alex Carter',
        email: 'admin@avexcrm.com',
      },
    },
    {
      id: 'mov_demo_02',
      companyId: 'comp_001',
      itemId: 'item_demo_01',
      type: 'STOCK_OUT',
      quantity: 6,
      reason: 'Issued to engineering onboarding batch Q1',
      performedByUserId: 'usr_002',
      createdAt: '2024-01-15T14:00:00.000Z',
      performedByUser: {
        id: 'usr_002',
        fullName: 'Sarah Jenkins',
        email: 'sarah@avexcrm.com',
      },
    },
    {
      id: 'mov_demo_03',
      companyId: 'comp_001',
      itemId: 'item_demo_02',
      type: 'STOCK_IN',
      quantity: 10,
      reason: 'Warehouse delivery shipment #WH-102',
      performedByUserId: 'user_owner_001',
      createdAt: '2024-02-15T10:00:00.000Z',
      performedByUser: {
        id: 'user_owner_001',
        fullName: 'Alex Carter',
        email: 'admin@avexcrm.com',
      },
    },
    {
      id: 'mov_demo_04',
      companyId: 'comp_001',
      itemId: 'item_demo_02',
      type: 'STOCK_OUT',
      quantity: 6,
      reason: 'Deploy to workspace pods 3 & 4',
      performedByUserId: 'usr_002',
      createdAt: '2024-02-20T11:00:00.000Z',
      performedByUser: {
        id: 'usr_002',
        fullName: 'Sarah Jenkins',
        email: 'sarah@avexcrm.com',
      },
    },
  ],
};
